/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/nim-0.17.0/lib -o /Users/antonin/exercism/nim/hello-world/nimcache/helloworld_test.o /Users/antonin/exercism/nim/hello-world/nimcache/helloworld_test.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <setjmp.h>
#include <string.h>
#include <stdlib.h>
#undef linux
#undef near
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY_sM4lkSb7zS6F7OVMvW9cffQ TY_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct CellSeq_Axo1XVm9aaQueTOldv8le5w CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct GcHeap_1TRH1TZMaVZTnLNcIHuNFQ GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct GcStack_7fytPA5bBsob6See21YMRA GcStack_7fytPA5bBsob6See21YMRA;
typedef struct MemRegion_x81NhDv59b8ercDZ9bi85jyg MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct SmallChunk_tXn60W2f8h3jgAYdEmy5NQ SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct LLChunk_XsENErzHIZV9bhvyJx56wGw LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct BigChunk_Rv9c70Uhp2TytkX7eH78qEg BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct IntSet_EZObFrE3NC9bIb3YMkY9crZA IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct AvlNode_IaqjtwKhxLEpvDS9bct9blEw AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct TY_ujsjpB2O9cjj3uDHsXbnSzg TY_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct GcStat_0RwLoVBHZPfUAcLczmfQAg GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct CellSet_jG87P0AI9aZtss9ccTYBIISQ CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct PageDesc_fublkgIY4LG3mT51LU2WHg PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw;
typedef struct TY_2gM6knqz8MaAY9c4MAR2ztg TY_2gM6knqz8MaAY9c4MAR2ztg;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TSafePoint TSafePoint;
typedef struct TestResult_GEvSVSxdPWWgMGM48ywEYQ TestResult_GEvSVSxdPWWgMGM48ywEYQ;
typedef struct JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ;
typedef struct ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw;
typedef struct BaseChunk_Sdq7WpT6qAH858F5ZEdG3w BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct FreeCell_u6M5LHprqzkn9axr04yg9bGQ FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct StreamObj_RShkcoDOPnoCVhtpN1hDPQ StreamObj_RShkcoDOPnoCVhtpN1hDPQ;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct  TNimType  {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell_1zcF9cV8XIAtbN8h5HRUB8g  {
NI refcount;
TNimType* typ;
};
struct  GcStack_7fytPA5bBsob6See21YMRA  {
void* bottom;
};
struct  CellSeq_Axo1XVm9aaQueTOldv8le5w  {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct  IntSet_EZObFrE3NC9bIb3YMkY9crZA  {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef AvlNode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct  AvlNode_IaqjtwKhxLEpvDS9bct9blEw  {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct TY_ujsjpB2O9cjj3uDHsXbnSzg {
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef TY_ujsjpB2O9cjj3uDHsXbnSzg TY_LzOv2eCDGiceMKQstCLmhw[30];
struct  HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg  {
NI len;
TY_LzOv2eCDGiceMKQstCLmhw chunks;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct  MemRegion_x81NhDv59b8ercDZ9bi85jyg  {
NI minLargeObj;
NI maxLargeObj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct  GcStat_0RwLoVBHZPfUAcLczmfQAg  {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct  CellSet_jG87P0AI9aZtss9ccTYBIISQ  {
NI counter;
NI max;
PageDesc_fublkgIY4LG3mT51LU2WHg* head;
PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct  GcHeap_1TRH1TZMaVZTnLNcIHuNFQ  {
GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
typedef NU8 TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ;
typedef N_NIMCALL_PTR(void, TY_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} TY_KeeAOYBd84Ofsw6Y7LizaQ;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
struct  TestResult_GEvSVSxdPWWgMGM48ywEYQ  {
NimStringDesc* suiteName;
NimStringDesc* testName;
TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ status;
};
struct  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w  {
NI prevSize;
NI size;
};
struct  SmallChunk_tXn60W2f8h3jgAYdEmy5NQ  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct  LLChunk_XsENErzHIZV9bhvyJx56wGw  {
NI size;
NI acc;
LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct  BigChunk_Rv9c70Uhp2TytkX7eH78qEg  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct  Trunk_W0r8S0Y3UGke6T9bIUWnnuw  {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  PageDesc_fublkgIY4LG3mT51LU2WHg  {
PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw  {
  TNimObject Sup;
};
struct  JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ  {
  OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw Sup;
StreamObj_RShkcoDOPnoCVhtpN1hDPQ* stream;
TY_sM4lkSb7zS6F7OVMvW9cffQ* testErrors;
NF testStartTime;
NimStringDesc* testStackTrace;
};
typedef NU8 OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww;
struct  ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw  {
  OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw Sup;
NIM_BOOL colorOutput;
OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww outputLevel;
NIM_BOOL isInSuite;
NIM_BOOL isInTest;
};
struct  FreeCell_u6M5LHprqzkn9axr04yg9bGQ  {
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
typedef N_NIMCALL_PTR(void, TY_cnkJEp9bna8U6yi9aVW9cAJ0Q) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY_KjFcmLOhf4VQvVcyLJWXZw) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(void, TY_jlOYFw9cHausuCbPoWx2iiA) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY_Xzm85qBLb9cf9cu8VOfAr8PQ) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NI, TY_tjaJtoUzLe1BMUbItlcGhQ) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, TY_b9bsIuILxTLVZHPvJBW187A) (StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
struct  StreamObj_RShkcoDOPnoCVhtpN1hDPQ  {
  TNimObject Sup;
TY_cnkJEp9bna8U6yi9aVW9cAJ0Q closeImpl;
TY_KjFcmLOhf4VQvVcyLJWXZw atEndImpl;
TY_jlOYFw9cHausuCbPoWx2iiA setPositionImpl;
TY_Xzm85qBLb9cf9cu8VOfAr8PQ getPositionImpl;
TY_tjaJtoUzLe1BMUbItlcGhQ readDataImpl;
TY_tjaJtoUzLe1BMUbItlcGhQ peekDataImpl;
TY_b9bsIuILxTLVZHPvJBW187A writeDataImpl;
TY_cnkJEp9bna8U6yi9aVW9cAJ0Q flushImpl;
};
struct TY_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct TY_2gM6knqz8MaAY9c4MAR2ztg {
  TGenericSeq Sup;
  OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, ensureFormattersInitialized_8zybqvexf9aYkm9bmgyU3eLg)(void);
N_NIMCALL(NIM_BOOL, shouldRun_ONH9bpFQB7Lkusu9bdW9bZB9bg)(NimStringDesc* testName);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(CellSeq_Axo1XVm9aaQueTOldv8le5w* s, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_3)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(TY_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, testStarted_9bXmL9b2zT9aAVv9c8Tm6AvWog)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* testName);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_7)(void);
N_NIMCALL(NimStringDesc*, helloworld_gsKQNDh3DKS9bk2U4dhinhw)(NimStringDesc* name);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_NIMCALL(void, checkpoint_4nBz3prx9cKVVOoTZb4rNCQ)(NimStringDesc* msg);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_12)(void);
N_NIMCALL(void, failureOccurred_i9ctYnjK2z9bxX9cq0gYct9cIA)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, TY_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
static N_INLINE(NimStringDesc*, getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qsystem)(void);
static N_INLINE(Exception*, getCurrentException)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_16)(void);
N_NIMCALL(NimStringDesc*, getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA)(Exception* e);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_17)(void);
static N_INLINE(void, popCurrentException)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_20)(void);
N_NIMCALL(void, testEnded_xoIS1BdhYWQ6hhMP22XXiw)(TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult);
N_NIMCALL(void, reraiseException)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_22)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_25)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_30)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_32)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_33)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_36)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_38)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_41)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_46)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_48)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_49)(void);
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_52)(void);
N_NIMCALL(void, chckNilDisp)(void* p);
static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_NOINLINE(NIM_BOOL, isObjSlowPath_k9bdq9bQE075AR7scLFt5wIg)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_NIMCALL(void, suiteStarted_9aAyDoHTMoiLoSiMpkUAFNw)(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, NimStringDesc* suiteName);
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
N_NIMCALL(void, suiteStarted_IXWI0IZVUaexE074PboPzQ)(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, NimStringDesc* suiteName);
N_NIMCALL(void, suiteStarted_zvRCVP5x4ZBpPV2Xx9cPHZA)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* suiteName);
N_NIMCALL(void, testStarted_EYS8dFM0pZmDNdV9c1cyo4Q)(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, NimStringDesc* testName);
N_NIMCALL(void, testStarted_0WlfvTsMUPRHUfLeuXrGAg)(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, NimStringDesc* testName);
N_NIMCALL(void, testStarted_YRuPwQXlDxZko9bSMypk3hA)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* testName);
N_NIMCALL(void, failureOccurred_NAlHeCfOfz1bBvtw2rCPGw)(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, TY_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_NIMCALL(void, failureOccurred_HopmjhtOQil8N9axQ5kNI3w)(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, TY_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_NIMCALL(void, failureOccurred_Fsq9aCTSjbGiV7TYpR757Lw)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, TY_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_NIMCALL(void, testEnded_E5f9a05hVCAPvYslPV2f4TQ)(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult);
N_NIMCALL(void, testEnded_AsoOYSa1sGgPTBsUoT9cxsw)(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult);
N_NIMCALL(void, testEnded_hPRwDS9aOIRJ5MB9buAX30Wg)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult);
N_NIMCALL(void, suiteEnded_EF53BADEiH9a6amiy7eitMg_2)(JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter);
N_NIMCALL(void, suiteEnded_IIGQUyJJjT9cNV9c34JPjWGA)(ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter);
N_NIMCALL(void, suiteEnded_RS3dEHKAbuhOugXu1dXVHg)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_termiosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_termiosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_terminalInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_terminalDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unittestInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unittestDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_helloworldInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_helloworldDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, helloworld_testDatInit000)(void);
extern TY_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q;
OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_6vZ0eCyziJIpjOJxE6ZZSA;
extern TNimType NTI_po6hYFavJCZm28qf1dR3mw_;
extern TY_2gM6knqz8MaAY9c4MAR2ztg* formatters_55U7g4zhjHV9bCI6emTgDiA;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
NimStringDesc* colonc1__WzG62vRKCCCuEmzM9bJ2gjA;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_6vZ0eCyziJIpjOJxE6ZZSA_2;
extern NIM_BOOL abortOnError_Bte3Uiwc4Q19ago2N4C89cUA;
extern NI nim_program_result;
extern Exception* currException_9bVPeDJlYTi9bQApZpfH8wjg;
NimStringDesc* stackTrace_yo79audNUOaALqoPY6lz8tQ;
OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_6vZ0eCyziJIpjOJxE6ZZSA_3;
TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult_zKJcLcg3TmFPRC7R7c9cT9bg;
extern TNimType NTI_GEvSVSxdPWWgMGM48ywEYQ_;
TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_2;
OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_6vZ0eCyziJIpjOJxE6ZZSA_4;
NimStringDesc* colonc1__WzG62vRKCCCuEmzM9bJ2gjA_2;
OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_6vZ0eCyziJIpjOJxE6ZZSA_5;
NimStringDesc* stackTrace_yo79audNUOaALqoPY6lz8tQ_2;
OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_6vZ0eCyziJIpjOJxE6ZZSA_6;
TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult_zKJcLcg3TmFPRC7R7c9cT9bg_2;
TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_3;
OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_6vZ0eCyziJIpjOJxE6ZZSA_7;
NimStringDesc* colonc1__WzG62vRKCCCuEmzM9bJ2gjA_3;
OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_6vZ0eCyziJIpjOJxE6ZZSA_8;
NimStringDesc* stackTrace_yo79audNUOaALqoPY6lz8tQ_3;
OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter_6vZ0eCyziJIpjOJxE6ZZSA_9;
TestResult_GEvSVSxdPWWgMGM48ywEYQ testResult_zKJcLcg3TmFPRC7R7c9cT9bg_3;
extern TNimType NTI_kvLOVRX6Za2S0C2QxHXy9cQ_;
static TNimType* Nim_OfCheck_CACHE54[2];
extern TNimType NTI_dU6QGtP3KgqXg9bZP3nhpWw_;
static TNimType* Nim_OfCheck_CACHE55[2];
extern TNimType NTI_dLGU9cWWYqlqOn8lpRVsx9cw_;
static TNimType* Nim_OfCheck_CACHE56[2];
static TNimType* Nim_OfCheck_CACHE57[2];
static TNimType* Nim_OfCheck_CACHE58[2];
static TNimType* Nim_OfCheck_CACHE59[2];
static TNimType* Nim_OfCheck_CACHE60[2];
static TNimType* Nim_OfCheck_CACHE61[2];
static TNimType* Nim_OfCheck_CACHE62[2];
static TNimType* Nim_OfCheck_CACHE63[2];
static TNimType* Nim_OfCheck_CACHE64[2];
static TNimType* Nim_OfCheck_CACHE65[2];
static TNimType* Nim_OfCheck_CACHE66[2];
static TNimType* Nim_OfCheck_CACHE67[2];
static TNimType* Nim_OfCheck_CACHE68[2];
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_2, "no name", 7);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_5, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_8, "World", 5);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_9, "Hello, World!", 13);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_10, "helloworld_test.nim(6,21): Check failed: helloworld() == \"Hello"
", World!\"", 72);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_11, "helloworld() was ", 17);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_14, "Unhandled exception: ", 21);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_15, "", 0);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_21, "sample name", 11);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_26, "Alice", 5);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_27, "Hello, Alice!", 13);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_28, "helloworld_test.nim(9,28): Check failed: helloworld(\"Alice\") =="
" \"Hello, Alice!\"", 79);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_29, "helloworld(\"Alice\") was ", 24);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_37, "other sample name", 17);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_42, "Bob", 3);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_43, "Hello, Bob!", 11);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_44, "helloworld_test.nim(12,26): Check failed: helloworld(\"Bob\") == "
"\"Hello, Bob!\"", 76);
STRING_LITERAL(TM_4qp2gZX9anqPB0kpcB8Cugw_45, "helloworld(\"Bob\") was ", 22);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim")
	result = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim")
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim")
	nimln_(270, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(272, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(273, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_3)(void) {
	nimGCvisit((void*)formatter_6vZ0eCyziJIpjOJxE6ZZSA, 0);
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim")
	nimln_(196, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim")
	nimln_(223, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(224, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim")
	nimln_(281, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(363, "system.nim");
		nimln_(281, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(282, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(363, "system.nim");
		nimln_(282, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(283, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_7)(void) {
	nimGCvisit((void*)colonc1__WzG62vRKCCCuEmzM9bJ2gjA, 0);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim")
	nimln_(288, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(363, "system.nim");
		nimln_(288, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(289, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(290, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(291, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(363, "system.nim");
		nimln_(291, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(292, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(293, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(294, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(295, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_12)(void) {
	nimGCvisit((void*)formatter_6vZ0eCyziJIpjOJxE6ZZSA_2, 0);
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	nimfr_("getCurrentException", "system.nim")
	result = (Exception*)0;
	nimln_(3171, "system.nim");
	result = currException_9bVPeDJlYTi9bQApZpfH8wjg;
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qsystem)(void) {
	NimStringDesc* result;
	Exception* e;
	nimfr_("getCurrentExceptionMsg", "system.nim")
{	result = (NimStringDesc*)0;
	nimln_(3176, "system.nim");
	e = getCurrentException();
	nimln_(3177, "system.nim");
	{
		if (!(e == NIM_NIL)) goto LA3_;
		result = copyString(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_15));
	}
	goto LA1_;
	LA3_: ;
	{
		result = copyString((*e).message);
	}
	LA1_: ;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_16)(void) {
	nimGCvisit((void*)stackTrace_yo79audNUOaALqoPY6lz8tQ, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_17)(void) {
	nimGCvisit((void*)formatter_6vZ0eCyziJIpjOJxE6ZZSA_3, 0);
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currException_9bVPeDJlYTi9bQApZpfH8wjg), NIM_NIL);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_20)(void) {
	nimGCvisit((void*)testResult_zKJcLcg3TmFPRC7R7c9cT9bg.suiteName, 0);
	nimGCvisit((void*)testResult_zKJcLcg3TmFPRC7R7c9cT9bg.testName, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_22)(void) {
	nimGCvisit((void*)formatter_6vZ0eCyziJIpjOJxE6ZZSA_4, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_25)(void) {
	nimGCvisit((void*)colonc1__WzG62vRKCCCuEmzM9bJ2gjA_2, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_30)(void) {
	nimGCvisit((void*)formatter_6vZ0eCyziJIpjOJxE6ZZSA_5, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_32)(void) {
	nimGCvisit((void*)stackTrace_yo79audNUOaALqoPY6lz8tQ_2, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_33)(void) {
	nimGCvisit((void*)formatter_6vZ0eCyziJIpjOJxE6ZZSA_6, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_36)(void) {
	nimGCvisit((void*)testResult_zKJcLcg3TmFPRC7R7c9cT9bg_2.suiteName, 0);
	nimGCvisit((void*)testResult_zKJcLcg3TmFPRC7R7c9cT9bg_2.testName, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_38)(void) {
	nimGCvisit((void*)formatter_6vZ0eCyziJIpjOJxE6ZZSA_7, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_41)(void) {
	nimGCvisit((void*)colonc1__WzG62vRKCCCuEmzM9bJ2gjA_3, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_46)(void) {
	nimGCvisit((void*)formatter_6vZ0eCyziJIpjOJxE6ZZSA_8, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_48)(void) {
	nimGCvisit((void*)stackTrace_yo79audNUOaALqoPY6lz8tQ_3, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_49)(void) {
	nimGCvisit((void*)formatter_6vZ0eCyziJIpjOJxE6ZZSA_9, 0);
}
static N_NIMCALL(void, TM_4qp2gZX9anqPB0kpcB8Cugw_52)(void) {
	nimGCvisit((void*)testResult_zKJcLcg3TmFPRC7R7c9cT9bg_3.suiteName, 0);
	nimGCvisit((void*)testResult_zKJcLcg3TmFPRC7R7c9cT9bg_3.testName, 0);
}

static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	{
		if (!(obj == subclass)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		if (!((*obj).base == subclass)) goto LA7_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA7_: ;
	{
		if (!(cache[(((NI) 0))- 0] == obj)) goto LA11_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA11_: ;
	{
		if (!(cache[(((NI) 1))- 0] == obj)) goto LA15_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA15_: ;
	result = isObjSlowPath_k9bdq9bQE075AR7scLFt5wIg(obj, subclass, cache);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(void, suiteStarted_GgW0QiD89cMFXShyPQ8t8qg)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* suiteName) {
	nimfr_("suiteStarted", "unittest.nim")
	nimln_(118, "unittest.nim");
	chckNilDisp(formatter);
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_), Nim_OfCheck_CACHE54)))) goto LA3_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_));
		suiteStarted_9aAyDoHTMoiLoSiMpkUAFNw(((JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*) (formatter)), suiteName);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_), Nim_OfCheck_CACHE55)))) goto LA6_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_));
		suiteStarted_IXWI0IZVUaexE074PboPzQ(((ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*) (formatter)), suiteName);
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_), Nim_OfCheck_CACHE56)))) goto LA9_;
		suiteStarted_zvRCVP5x4ZBpPV2Xx9cPHZA(formatter, suiteName);
	}
	goto LA1_;
	LA9_: ;
	LA1_: ;
	popFrame();
}

N_NIMCALL(void, testStarted_9bXmL9b2zT9aAVv9c8Tm6AvWog)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* testName) {
	nimfr_("testStarted", "unittest.nim")
	nimln_(120, "unittest.nim");
	chckNilDisp(formatter);
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_), Nim_OfCheck_CACHE57)))) goto LA3_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_));
		testStarted_EYS8dFM0pZmDNdV9c1cyo4Q(((JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*) (formatter)), testName);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_), Nim_OfCheck_CACHE58)))) goto LA6_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_));
		testStarted_0WlfvTsMUPRHUfLeuXrGAg(((ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*) (formatter)), testName);
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_), Nim_OfCheck_CACHE59)))) goto LA9_;
		testStarted_YRuPwQXlDxZko9bSMypk3hA(formatter, testName);
	}
	goto LA1_;
	LA9_: ;
	LA1_: ;
	popFrame();
}

N_NIMCALL(void, failureOccurred_i9ctYnjK2z9bxX9cq0gYct9cIA)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, TY_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace) {
	nimfr_("failureOccurred", "unittest.nim")
	nimln_(122, "unittest.nim");
	chckNilDisp(formatter);
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_), Nim_OfCheck_CACHE60)))) goto LA3_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_));
		failureOccurred_NAlHeCfOfz1bBvtw2rCPGw(((JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*) (formatter)), checkpoints, stackTrace);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_), Nim_OfCheck_CACHE61)))) goto LA6_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_));
		failureOccurred_HopmjhtOQil8N9axQ5kNI3w(((ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*) (formatter)), checkpoints, stackTrace);
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_), Nim_OfCheck_CACHE62)))) goto LA9_;
		failureOccurred_Fsq9aCTSjbGiV7TYpR757Lw(formatter, checkpoints, stackTrace);
	}
	goto LA1_;
	LA9_: ;
	LA1_: ;
	popFrame();
}

N_NIMCALL(void, testEnded_azSnnJ3hAiHHuUdLzViJlw)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult) {
	nimfr_("testEnded", "unittest.nim")
	nimln_(126, "unittest.nim");
	chckNilDisp(formatter);
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_), Nim_OfCheck_CACHE63)))) goto LA3_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_));
		testEnded_E5f9a05hVCAPvYslPV2f4TQ(((JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*) (formatter)), testResult);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_), Nim_OfCheck_CACHE64)))) goto LA6_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_));
		testEnded_AsoOYSa1sGgPTBsUoT9cxsw(((ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*) (formatter)), testResult);
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_), Nim_OfCheck_CACHE65)))) goto LA9_;
		testEnded_hPRwDS9aOIRJ5MB9buAX30Wg(formatter, testResult);
	}
	goto LA1_;
	LA9_: ;
	LA1_: ;
	popFrame();
}

N_NIMCALL(void, suiteEnded_K2O75e2roACICAuYiNImyw)(OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter) {
	nimfr_("suiteEnded", "unittest.nim")
	nimln_(128, "unittest.nim");
	chckNilDisp(formatter);
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_), Nim_OfCheck_CACHE66)))) goto LA3_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_kvLOVRX6Za2S0C2QxHXy9cQ_));
		suiteEnded_EF53BADEiH9a6amiy7eitMg_2(((JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ*) (formatter)));
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_), Nim_OfCheck_CACHE67)))) goto LA6_;
		if (formatter) chckObj((*formatter).Sup.m_type, (&NTI_dU6QGtP3KgqXg9bZP3nhpWw_));
		suiteEnded_IIGQUyJJjT9cNV9c34JPjWGA(((ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw*) (formatter)));
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((formatter) && (isObjWithCache((*formatter).Sup.m_type, (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_), Nim_OfCheck_CACHE68)))) goto LA9_;
		suiteEnded_RS3dEHKAbuhOugXu1dXVHg(formatter);
	}
	goto LA1_;
	LA9_: ;
	LA1_: ;
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_macrosDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_streamsDatInit000();
	stdlib_timesDatInit000();
	stdlib_posixDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_termiosDatInit000();
	stdlib_terminalDatInit000();
	stdlib_unittestDatInit000();
	unknown_helloworldDatInit000();
	helloworld_testDatInit000();
	stdlib_macrosInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_streamsInit000();
	stdlib_timesInit000();
	stdlib_posixInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_termiosInit000();
	stdlib_terminalInit000();
	stdlib_unittestInit000();
	unknown_helloworldInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("helloworld_test", "helloworld_test.nim")
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_3);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_7);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_12);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_16);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_17);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_20);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_22);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_25);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_30);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_32);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_33);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_36);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_38);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_41);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_46);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_48);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_49);
nimRegisterGlobalMarker(TM_4qp2gZX9anqPB0kpcB8Cugw_52);
	nimln_(375, "unittest.nim");
	ensureFormattersInitialized_8zybqvexf9aYkm9bmgyU3eLg();
	nimln_(5, "helloworld_test.nim");
	{
		NIM_BOOL T3_;
		TSafePoint TM_4qp2gZX9anqPB0kpcB8Cugw_6;
		T3_ = (NIM_BOOL)0;
		T3_ = shouldRun_ONH9bpFQB7Lkusu9bdW9bZB9bg(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_2));
		if (!T3_) goto LA4_;
		nimln_(378, "unittest.nim");
		if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ);
		checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
		nimln_(379, "unittest.nim");
		testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q = ((TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 0);
		{
			NI i;
			NI L;
			nimln_(3580, "system.nim");
			i = ((NI) 0);
			nimln_(3581, "system.nim");
			L = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
			{
				nimln_(3582, "system.nim");
				while (1) {
					NI TM_4qp2gZX9anqPB0kpcB8Cugw_4;
					if (!(i < L)) goto LA8;
					nimln_(3583, "system.nim");
					if ((NU)(i) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
					asgnRef((void**) (&formatter_6vZ0eCyziJIpjOJxE6ZZSA), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i]);
					nimln_(382, "unittest.nim");
					testStarted_9bXmL9b2zT9aAVv9c8Tm6AvWog(formatter_6vZ0eCyziJIpjOJxE6ZZSA, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_2));
					nimln_(3584, "system.nim");
					TM_4qp2gZX9anqPB0kpcB8Cugw_4 = addInt(i, ((NI) 1));
					i = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_4);
					nimln_(3585, "system.nim");
					{
						if (!!(((formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0) == L))) goto LA11_;
						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_5));
					}
					LA11_: ;
				} LA8: ;
			}
		}
		nimln_(384, "unittest.nim");
		pushSafePoint(&TM_4qp2gZX9anqPB0kpcB8Cugw_6);
		TM_4qp2gZX9anqPB0kpcB8Cugw_6.status = _setjmp(TM_4qp2gZX9anqPB0kpcB8Cugw_6.context);
		if (TM_4qp2gZX9anqPB0kpcB8Cugw_6.status == 0) {
			{
				nimln_(497, "unittest.nim");
				asgnRefNoCycle((void**) (&colonc1__WzG62vRKCCCuEmzM9bJ2gjA), helloworld_gsKQNDh3DKS9bk2U4dhinhw(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_8)));
				nimln_(541, "unittest.nim");
				{
					NimStringDesc* T19_;
					nimln_(548, "unittest.nim");
					nimln_(521, "unittest.nim");
					if (!!(eqStrings(colonc1__WzG62vRKCCCuEmzM9bJ2gjA, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_9)))) goto LA17_;
					nimln_(542, "unittest.nim");
					checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_10));
					nimln_(502, "unittest.nim");
					T19_ = (NimStringDesc*)0;
					nimln_(521, "unittest.nim");
					T19_ = rawNewString(colonc1__WzG62vRKCCCuEmzM9bJ2gjA->Sup.len + 17);
appendString(T19_, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_11));
appendString(T19_, colonc1__WzG62vRKCCCuEmzM9bJ2gjA);
					checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(T19_);
					nimln_(439, "unittest.nim");
					testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q = ((TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1);
					nimln_(443, "unittest.nim");
					ensureFormattersInitialized_8zybqvexf9aYkm9bmgyU3eLg();
					{
						NI volatile i_2;
						NI L_2;
						nimln_(3580, "system.nim");
						i_2 = ((NI) 0);
						nimln_(3581, "system.nim");
						L_2 = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
						{
							nimln_(3582, "system.nim");
							while (1) {
								NI TM_4qp2gZX9anqPB0kpcB8Cugw_13;
								if (!(i_2 < L_2)) goto LA22;
								nimln_(3583, "system.nim");
								if ((NU)(i_2) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
								asgnRef((void**) (&formatter_6vZ0eCyziJIpjOJxE6ZZSA_2), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i_2]);
								nimln_(450, "unittest.nim");
								failureOccurred_i9ctYnjK2z9bxX9cq0gYct9cIA(formatter_6vZ0eCyziJIpjOJxE6ZZSA_2, checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ, NIM_NIL);
								nimln_(3584, "system.nim");
								TM_4qp2gZX9anqPB0kpcB8Cugw_13 = addInt(i_2, ((NI) 1));
								i_2 = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_13);
								nimln_(3585, "system.nim");
								{
									if (!!(((formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0) == L_2))) goto LA25_;
									failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_5));
								}
								LA25_: ;
							} LA22: ;
						}
					}
					nimln_(453, "unittest.nim");
					{
						if (!abortOnError_Bte3Uiwc4Q19ago2N4C89cUA) goto LA29_;
						exit(nim_program_result);
					}
					LA29_: ;
					nimln_(455, "unittest.nim");
					if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ);
					checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
				}
				LA17_: ;
			}
			popSafePoint();
		}
		else {
			popSafePoint();
			setFrame((TFrame*)&FR_);
			{
				NimStringDesc* T33_;
				NimStringDesc* T34_;
				Exception* T35_;
				TM_4qp2gZX9anqPB0kpcB8Cugw_6.status = 0;
				nimln_(392, "unittest.nim");
				T33_ = (NimStringDesc*)0;
				T34_ = (NimStringDesc*)0;
				T34_ = getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qsystem();
				T33_ = rawNewString(T34_->Sup.len + 21);
appendString(T33_, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_14));
appendString(T33_, T34_);
				checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(T33_);
				nimln_(393, "unittest.nim");
				T35_ = (Exception*)0;
				T35_ = getCurrentException();
				asgnRefNoCycle((void**) (&stackTrace_yo79audNUOaALqoPY6lz8tQ), getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA(T35_));
				nimln_(439, "unittest.nim");
				testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q = ((TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1);
				nimln_(443, "unittest.nim");
				ensureFormattersInitialized_8zybqvexf9aYkm9bmgyU3eLg();
				{
					NI i_3;
					NI L_3;
					nimln_(3580, "system.nim");
					i_3 = ((NI) 0);
					nimln_(3581, "system.nim");
					L_3 = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
					{
						nimln_(3582, "system.nim");
						while (1) {
							NI TM_4qp2gZX9anqPB0kpcB8Cugw_18;
							if (!(i_3 < L_3)) goto LA38;
							nimln_(3583, "system.nim");
							if ((NU)(i_3) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
							asgnRef((void**) (&formatter_6vZ0eCyziJIpjOJxE6ZZSA_3), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i_3]);
							nimln_(448, "unittest.nim");
							failureOccurred_i9ctYnjK2z9bxX9cq0gYct9cIA(formatter_6vZ0eCyziJIpjOJxE6ZZSA_3, checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ, stackTrace_yo79audNUOaALqoPY6lz8tQ);
							nimln_(3584, "system.nim");
							TM_4qp2gZX9anqPB0kpcB8Cugw_18 = addInt(i_3, ((NI) 1));
							i_3 = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_18);
							nimln_(3585, "system.nim");
							{
								if (!!(((formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0) == L_3))) goto LA41_;
								failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_5));
							}
							LA41_: ;
						} LA38: ;
					}
				}
				nimln_(453, "unittest.nim");
				{
					if (!abortOnError_Bte3Uiwc4Q19ago2N4C89cUA) goto LA45_;
					exit(nim_program_result);
				}
				LA45_: ;
				nimln_(455, "unittest.nim");
				if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ);
				checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
				popCurrentException();
			}
		}
		{
			TestResult_GEvSVSxdPWWgMGM48ywEYQ T52_;
			nimln_(397, "unittest.nim");
			{
				NI TM_4qp2gZX9anqPB0kpcB8Cugw_19;
				if (!(testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q == ((TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1))) goto LA50_;
				nimln_(398, "unittest.nim");
				TM_4qp2gZX9anqPB0kpcB8Cugw_19 = addInt(nim_program_result, ((NI) 1));
				nim_program_result = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_19);
			}
			LA50_: ;
			nimln_(399, "unittest.nim");
			memset((void*)(&T52_), 0, sizeof(T52_));
			memset((void*)(&T52_), 0, sizeof(T52_));
			T52_.suiteName = copyString(NIM_NIL);
			T52_.testName = copyString(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_2));
			T52_.status = testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q;
			asgnRefNoCycle((void**) (&testResult_zKJcLcg3TmFPRC7R7c9cT9bg.suiteName), T52_.suiteName);
			asgnRefNoCycle((void**) (&testResult_zKJcLcg3TmFPRC7R7c9cT9bg.testName), T52_.testName);
			testResult_zKJcLcg3TmFPRC7R7c9cT9bg.status = T52_.status;
			nimln_(404, "unittest.nim");
			testEnded_xoIS1BdhYWQ6hhMP22XXiw((&testResult_zKJcLcg3TmFPRC7R7c9cT9bg));
			nimln_(405, "unittest.nim");
			if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ);
			checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
		}
		if (TM_4qp2gZX9anqPB0kpcB8Cugw_6.status != 0) reraiseException();
	}
	LA4_: ;
	nimln_(375, "unittest.nim");
	ensureFormattersInitialized_8zybqvexf9aYkm9bmgyU3eLg();
	nimln_(8, "helloworld_test.nim");
	{
		NIM_BOOL T55_;
		TSafePoint TM_4qp2gZX9anqPB0kpcB8Cugw_24;
		T55_ = (NIM_BOOL)0;
		T55_ = shouldRun_ONH9bpFQB7Lkusu9bdW9bZB9bg(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_21));
		if (!T55_) goto LA56_;
		nimln_(378, "unittest.nim");
		if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ);
		checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
		nimln_(379, "unittest.nim");
		testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_2 = ((TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 0);
		{
			NI i_4;
			NI L_4;
			nimln_(3580, "system.nim");
			i_4 = ((NI) 0);
			nimln_(3581, "system.nim");
			L_4 = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
			{
				nimln_(3582, "system.nim");
				while (1) {
					NI TM_4qp2gZX9anqPB0kpcB8Cugw_23;
					if (!(i_4 < L_4)) goto LA60;
					nimln_(3583, "system.nim");
					if ((NU)(i_4) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
					asgnRef((void**) (&formatter_6vZ0eCyziJIpjOJxE6ZZSA_4), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i_4]);
					nimln_(382, "unittest.nim");
					testStarted_9bXmL9b2zT9aAVv9c8Tm6AvWog(formatter_6vZ0eCyziJIpjOJxE6ZZSA_4, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_21));
					nimln_(3584, "system.nim");
					TM_4qp2gZX9anqPB0kpcB8Cugw_23 = addInt(i_4, ((NI) 1));
					i_4 = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_23);
					nimln_(3585, "system.nim");
					{
						if (!!(((formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0) == L_4))) goto LA63_;
						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_5));
					}
					LA63_: ;
				} LA60: ;
			}
		}
		nimln_(384, "unittest.nim");
		pushSafePoint(&TM_4qp2gZX9anqPB0kpcB8Cugw_24);
		TM_4qp2gZX9anqPB0kpcB8Cugw_24.status = _setjmp(TM_4qp2gZX9anqPB0kpcB8Cugw_24.context);
		if (TM_4qp2gZX9anqPB0kpcB8Cugw_24.status == 0) {
			{
				nimln_(497, "unittest.nim");
				asgnRefNoCycle((void**) (&colonc1__WzG62vRKCCCuEmzM9bJ2gjA_2), helloworld_gsKQNDh3DKS9bk2U4dhinhw(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_26)));
				nimln_(541, "unittest.nim");
				{
					NimStringDesc* T71_;
					nimln_(548, "unittest.nim");
					nimln_(521, "unittest.nim");
					if (!!(eqStrings(colonc1__WzG62vRKCCCuEmzM9bJ2gjA_2, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_27)))) goto LA69_;
					nimln_(542, "unittest.nim");
					checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_28));
					nimln_(502, "unittest.nim");
					T71_ = (NimStringDesc*)0;
					nimln_(521, "unittest.nim");
					T71_ = rawNewString(colonc1__WzG62vRKCCCuEmzM9bJ2gjA_2->Sup.len + 24);
appendString(T71_, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_29));
appendString(T71_, colonc1__WzG62vRKCCCuEmzM9bJ2gjA_2);
					checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(T71_);
					nimln_(439, "unittest.nim");
					testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_2 = ((TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1);
					nimln_(443, "unittest.nim");
					ensureFormattersInitialized_8zybqvexf9aYkm9bmgyU3eLg();
					{
						NI volatile i_5;
						NI L_5;
						nimln_(3580, "system.nim");
						i_5 = ((NI) 0);
						nimln_(3581, "system.nim");
						L_5 = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
						{
							nimln_(3582, "system.nim");
							while (1) {
								NI TM_4qp2gZX9anqPB0kpcB8Cugw_31;
								if (!(i_5 < L_5)) goto LA74;
								nimln_(3583, "system.nim");
								if ((NU)(i_5) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
								asgnRef((void**) (&formatter_6vZ0eCyziJIpjOJxE6ZZSA_5), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i_5]);
								nimln_(450, "unittest.nim");
								failureOccurred_i9ctYnjK2z9bxX9cq0gYct9cIA(formatter_6vZ0eCyziJIpjOJxE6ZZSA_5, checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ, NIM_NIL);
								nimln_(3584, "system.nim");
								TM_4qp2gZX9anqPB0kpcB8Cugw_31 = addInt(i_5, ((NI) 1));
								i_5 = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_31);
								nimln_(3585, "system.nim");
								{
									if (!!(((formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0) == L_5))) goto LA77_;
									failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_5));
								}
								LA77_: ;
							} LA74: ;
						}
					}
					nimln_(453, "unittest.nim");
					{
						if (!abortOnError_Bte3Uiwc4Q19ago2N4C89cUA) goto LA81_;
						exit(nim_program_result);
					}
					LA81_: ;
					nimln_(455, "unittest.nim");
					if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ);
					checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
				}
				LA69_: ;
			}
			popSafePoint();
		}
		else {
			popSafePoint();
			setFrame((TFrame*)&FR_);
			{
				NimStringDesc* T85_;
				NimStringDesc* T86_;
				Exception* T87_;
				TM_4qp2gZX9anqPB0kpcB8Cugw_24.status = 0;
				nimln_(392, "unittest.nim");
				T85_ = (NimStringDesc*)0;
				T86_ = (NimStringDesc*)0;
				T86_ = getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qsystem();
				T85_ = rawNewString(T86_->Sup.len + 21);
appendString(T85_, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_14));
appendString(T85_, T86_);
				checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(T85_);
				nimln_(393, "unittest.nim");
				T87_ = (Exception*)0;
				T87_ = getCurrentException();
				asgnRefNoCycle((void**) (&stackTrace_yo79audNUOaALqoPY6lz8tQ_2), getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA(T87_));
				nimln_(439, "unittest.nim");
				testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_2 = ((TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1);
				nimln_(443, "unittest.nim");
				ensureFormattersInitialized_8zybqvexf9aYkm9bmgyU3eLg();
				{
					NI i_6;
					NI L_6;
					nimln_(3580, "system.nim");
					i_6 = ((NI) 0);
					nimln_(3581, "system.nim");
					L_6 = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
					{
						nimln_(3582, "system.nim");
						while (1) {
							NI TM_4qp2gZX9anqPB0kpcB8Cugw_34;
							if (!(i_6 < L_6)) goto LA90;
							nimln_(3583, "system.nim");
							if ((NU)(i_6) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
							asgnRef((void**) (&formatter_6vZ0eCyziJIpjOJxE6ZZSA_6), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i_6]);
							nimln_(448, "unittest.nim");
							failureOccurred_i9ctYnjK2z9bxX9cq0gYct9cIA(formatter_6vZ0eCyziJIpjOJxE6ZZSA_6, checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ, stackTrace_yo79audNUOaALqoPY6lz8tQ_2);
							nimln_(3584, "system.nim");
							TM_4qp2gZX9anqPB0kpcB8Cugw_34 = addInt(i_6, ((NI) 1));
							i_6 = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_34);
							nimln_(3585, "system.nim");
							{
								if (!!(((formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0) == L_6))) goto LA93_;
								failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_5));
							}
							LA93_: ;
						} LA90: ;
					}
				}
				nimln_(453, "unittest.nim");
				{
					if (!abortOnError_Bte3Uiwc4Q19ago2N4C89cUA) goto LA97_;
					exit(nim_program_result);
				}
				LA97_: ;
				nimln_(455, "unittest.nim");
				if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ);
				checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
				popCurrentException();
			}
		}
		{
			TestResult_GEvSVSxdPWWgMGM48ywEYQ T104_;
			nimln_(397, "unittest.nim");
			{
				NI TM_4qp2gZX9anqPB0kpcB8Cugw_35;
				if (!(testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_2 == ((TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1))) goto LA102_;
				nimln_(398, "unittest.nim");
				TM_4qp2gZX9anqPB0kpcB8Cugw_35 = addInt(nim_program_result, ((NI) 1));
				nim_program_result = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_35);
			}
			LA102_: ;
			nimln_(399, "unittest.nim");
			memset((void*)(&T104_), 0, sizeof(T104_));
			memset((void*)(&T104_), 0, sizeof(T104_));
			T104_.suiteName = copyString(NIM_NIL);
			T104_.testName = copyString(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_21));
			T104_.status = testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_2;
			asgnRefNoCycle((void**) (&testResult_zKJcLcg3TmFPRC7R7c9cT9bg_2.suiteName), T104_.suiteName);
			asgnRefNoCycle((void**) (&testResult_zKJcLcg3TmFPRC7R7c9cT9bg_2.testName), T104_.testName);
			testResult_zKJcLcg3TmFPRC7R7c9cT9bg_2.status = T104_.status;
			nimln_(404, "unittest.nim");
			testEnded_xoIS1BdhYWQ6hhMP22XXiw((&testResult_zKJcLcg3TmFPRC7R7c9cT9bg_2));
			nimln_(405, "unittest.nim");
			if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ);
			checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
		}
		if (TM_4qp2gZX9anqPB0kpcB8Cugw_24.status != 0) reraiseException();
	}
	LA56_: ;
	nimln_(375, "unittest.nim");
	ensureFormattersInitialized_8zybqvexf9aYkm9bmgyU3eLg();
	nimln_(11, "helloworld_test.nim");
	{
		NIM_BOOL T107_;
		TSafePoint TM_4qp2gZX9anqPB0kpcB8Cugw_40;
		T107_ = (NIM_BOOL)0;
		T107_ = shouldRun_ONH9bpFQB7Lkusu9bdW9bZB9bg(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_37));
		if (!T107_) goto LA108_;
		nimln_(378, "unittest.nim");
		if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ);
		checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
		nimln_(379, "unittest.nim");
		testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_3 = ((TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 0);
		{
			NI i_7;
			NI L_7;
			nimln_(3580, "system.nim");
			i_7 = ((NI) 0);
			nimln_(3581, "system.nim");
			L_7 = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
			{
				nimln_(3582, "system.nim");
				while (1) {
					NI TM_4qp2gZX9anqPB0kpcB8Cugw_39;
					if (!(i_7 < L_7)) goto LA112;
					nimln_(3583, "system.nim");
					if ((NU)(i_7) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
					asgnRef((void**) (&formatter_6vZ0eCyziJIpjOJxE6ZZSA_7), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i_7]);
					nimln_(382, "unittest.nim");
					testStarted_9bXmL9b2zT9aAVv9c8Tm6AvWog(formatter_6vZ0eCyziJIpjOJxE6ZZSA_7, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_37));
					nimln_(3584, "system.nim");
					TM_4qp2gZX9anqPB0kpcB8Cugw_39 = addInt(i_7, ((NI) 1));
					i_7 = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_39);
					nimln_(3585, "system.nim");
					{
						if (!!(((formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0) == L_7))) goto LA115_;
						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_5));
					}
					LA115_: ;
				} LA112: ;
			}
		}
		nimln_(384, "unittest.nim");
		pushSafePoint(&TM_4qp2gZX9anqPB0kpcB8Cugw_40);
		TM_4qp2gZX9anqPB0kpcB8Cugw_40.status = _setjmp(TM_4qp2gZX9anqPB0kpcB8Cugw_40.context);
		if (TM_4qp2gZX9anqPB0kpcB8Cugw_40.status == 0) {
			{
				nimln_(497, "unittest.nim");
				asgnRefNoCycle((void**) (&colonc1__WzG62vRKCCCuEmzM9bJ2gjA_3), helloworld_gsKQNDh3DKS9bk2U4dhinhw(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_42)));
				nimln_(541, "unittest.nim");
				{
					NimStringDesc* T123_;
					nimln_(548, "unittest.nim");
					nimln_(521, "unittest.nim");
					if (!!(eqStrings(colonc1__WzG62vRKCCCuEmzM9bJ2gjA_3, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_43)))) goto LA121_;
					nimln_(542, "unittest.nim");
					checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_44));
					nimln_(502, "unittest.nim");
					T123_ = (NimStringDesc*)0;
					nimln_(521, "unittest.nim");
					T123_ = rawNewString(colonc1__WzG62vRKCCCuEmzM9bJ2gjA_3->Sup.len + 22);
appendString(T123_, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_45));
appendString(T123_, colonc1__WzG62vRKCCCuEmzM9bJ2gjA_3);
					checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(T123_);
					nimln_(439, "unittest.nim");
					testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_3 = ((TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1);
					nimln_(443, "unittest.nim");
					ensureFormattersInitialized_8zybqvexf9aYkm9bmgyU3eLg();
					{
						NI volatile i_8;
						NI L_8;
						nimln_(3580, "system.nim");
						i_8 = ((NI) 0);
						nimln_(3581, "system.nim");
						L_8 = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
						{
							nimln_(3582, "system.nim");
							while (1) {
								NI TM_4qp2gZX9anqPB0kpcB8Cugw_47;
								if (!(i_8 < L_8)) goto LA126;
								nimln_(3583, "system.nim");
								if ((NU)(i_8) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
								asgnRef((void**) (&formatter_6vZ0eCyziJIpjOJxE6ZZSA_8), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i_8]);
								nimln_(450, "unittest.nim");
								failureOccurred_i9ctYnjK2z9bxX9cq0gYct9cIA(formatter_6vZ0eCyziJIpjOJxE6ZZSA_8, checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ, NIM_NIL);
								nimln_(3584, "system.nim");
								TM_4qp2gZX9anqPB0kpcB8Cugw_47 = addInt(i_8, ((NI) 1));
								i_8 = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_47);
								nimln_(3585, "system.nim");
								{
									if (!!(((formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0) == L_8))) goto LA129_;
									failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_5));
								}
								LA129_: ;
							} LA126: ;
						}
					}
					nimln_(453, "unittest.nim");
					{
						if (!abortOnError_Bte3Uiwc4Q19ago2N4C89cUA) goto LA133_;
						exit(nim_program_result);
					}
					LA133_: ;
					nimln_(455, "unittest.nim");
					if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ);
					checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
				}
				LA121_: ;
			}
			popSafePoint();
		}
		else {
			popSafePoint();
			setFrame((TFrame*)&FR_);
			{
				NimStringDesc* T137_;
				NimStringDesc* T138_;
				Exception* T139_;
				TM_4qp2gZX9anqPB0kpcB8Cugw_40.status = 0;
				nimln_(392, "unittest.nim");
				T137_ = (NimStringDesc*)0;
				T138_ = (NimStringDesc*)0;
				T138_ = getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qsystem();
				T137_ = rawNewString(T138_->Sup.len + 21);
appendString(T137_, ((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_14));
appendString(T137_, T138_);
				checkpoint_4nBz3prx9cKVVOoTZb4rNCQ(T137_);
				nimln_(393, "unittest.nim");
				T139_ = (Exception*)0;
				T139_ = getCurrentException();
				asgnRefNoCycle((void**) (&stackTrace_yo79audNUOaALqoPY6lz8tQ_3), getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA(T139_));
				nimln_(439, "unittest.nim");
				testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_3 = ((TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1);
				nimln_(443, "unittest.nim");
				ensureFormattersInitialized_8zybqvexf9aYkm9bmgyU3eLg();
				{
					NI i_9;
					NI L_9;
					nimln_(3580, "system.nim");
					i_9 = ((NI) 0);
					nimln_(3581, "system.nim");
					L_9 = (formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
					{
						nimln_(3582, "system.nim");
						while (1) {
							NI TM_4qp2gZX9anqPB0kpcB8Cugw_50;
							if (!(i_9 < L_9)) goto LA142;
							nimln_(3583, "system.nim");
							if ((NU)(i_9) >= (NU)(formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len)) raiseIndexError();
							asgnRef((void**) (&formatter_6vZ0eCyziJIpjOJxE6ZZSA_9), formatters_55U7g4zhjHV9bCI6emTgDiA->data[i_9]);
							nimln_(448, "unittest.nim");
							failureOccurred_i9ctYnjK2z9bxX9cq0gYct9cIA(formatter_6vZ0eCyziJIpjOJxE6ZZSA_9, checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ, stackTrace_yo79audNUOaALqoPY6lz8tQ_3);
							nimln_(3584, "system.nim");
							TM_4qp2gZX9anqPB0kpcB8Cugw_50 = addInt(i_9, ((NI) 1));
							i_9 = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_50);
							nimln_(3585, "system.nim");
							{
								if (!!(((formatters_55U7g4zhjHV9bCI6emTgDiA ? formatters_55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0) == L_9))) goto LA145_;
								failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_5));
							}
							LA145_: ;
						} LA142: ;
					}
				}
				nimln_(453, "unittest.nim");
				{
					if (!abortOnError_Bte3Uiwc4Q19ago2N4C89cUA) goto LA149_;
					exit(nim_program_result);
				}
				LA149_: ;
				nimln_(455, "unittest.nim");
				if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ);
				checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
				popCurrentException();
			}
		}
		{
			TestResult_GEvSVSxdPWWgMGM48ywEYQ T156_;
			nimln_(397, "unittest.nim");
			{
				NI TM_4qp2gZX9anqPB0kpcB8Cugw_51;
				if (!(testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_3 == ((TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1))) goto LA154_;
				nimln_(398, "unittest.nim");
				TM_4qp2gZX9anqPB0kpcB8Cugw_51 = addInt(nim_program_result, ((NI) 1));
				nim_program_result = (NI)(TM_4qp2gZX9anqPB0kpcB8Cugw_51);
			}
			LA154_: ;
			nimln_(399, "unittest.nim");
			memset((void*)(&T156_), 0, sizeof(T156_));
			memset((void*)(&T156_), 0, sizeof(T156_));
			T156_.suiteName = copyString(NIM_NIL);
			T156_.testName = copyString(((NimStringDesc*) &TM_4qp2gZX9anqPB0kpcB8Cugw_37));
			T156_.status = testStatusIMPL_Q4qcz3YlFyWrLneTJlsS4Q_3;
			asgnRefNoCycle((void**) (&testResult_zKJcLcg3TmFPRC7R7c9cT9bg_3.suiteName), T156_.suiteName);
			asgnRefNoCycle((void**) (&testResult_zKJcLcg3TmFPRC7R7c9cT9bg_3.testName), T156_.testName);
			testResult_zKJcLcg3TmFPRC7R7c9cT9bg_3.status = T156_.status;
			nimln_(404, "unittest.nim");
			testEnded_xoIS1BdhYWQ6hhMP22XXiw((&testResult_zKJcLcg3TmFPRC7R7c9cT9bg_3));
			nimln_(405, "unittest.nim");
			if (checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ) nimGCunrefNoCycle(checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ);
			checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
		}
		if (TM_4qp2gZX9anqPB0kpcB8Cugw_40.status != 0) reraiseException();
	}
	LA108_: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, helloworld_testDatInit000)(void) {
}

